### ISSUE TITLE
Discussion: UTF-16?

### ISSUE THREAD

**Issue by krischik** [Blady-Com/UXStrings#1]
> Using Unbounded_Wide_String is quite being in the middle of the river might as well use Unbounded_Wide_Wide_String. In this latter case the memory penalty is heavy for only few accentuated character occurrences. So back to Unbounded_Wide_String but you'll miss the so essential emojis ;-)

Did you consider going the Microsoft Windows route and store UTF-16 characters inside Unbounded_Wide_String?

BTW: I inherited and implementation of encoding aware string from Björn Persson which seem to go that way.

https://sourceforge.net/p/adacl/git/ci/develop/tree/adacl_eastrings/

Sadly there is a GNAT bug preventing me from compiling the eastrings. Björn made them back in 2004 - so it's not a new issue Ada has.

**Comment by Blady-Com** [comment]
> Did you consider going the Microsoft Windows route and store UTF-16 characters inside Unbounded_Wide_String?

Storing UTF-8 or UTF-16 leads to the same penalty: you can't access characters by direct indexing but by running from the beginning and counting characters until the wanted index.
For now I choose UTF-8 which one main advantage is its direct conversion to UTF-8 (main used external format for files or web).
UXStrings version 5.0 brings a third implementation with storing Unicode characters and benefits from direct indexing in term of performance (see more on [Ada Reddit](https://www.reddit.com/r/ada/comments/12gdpay/ann_release_of_uxstrings_50)).

> BTW: I inherited and implementation of encoding aware string from Björn Persson which seem to go that way.
> https://sourceforge.net/p/adacl/git/ci/develop/tree/adacl_eastrings/

Interesting concept of adapting internal representation of strings. I would like something similar for UXStrings. I'll keep the pointer, thanks.
